---
- hosts: demo
  user: ansible
  become: yes
  connection: ssh
  tasks:
        - name: make dir. nginx
          file:
               path: /etc/nginx
               state: directory
              
        - name: copy nginx.conf file
          copy:
               src: /var/lib/jenkins/workspace/ansible/nginx.conf
               dest: /etc/nginx/
        
        - name: copy index.html file
          copy: 
               src: /var/lib/jenkins/workspace/ansible/index.html
               dest: /var/www/html/
        
        - name: copy script.sh file
          copy: 
               src: /var/lib/jenkins/workspace/ansible/script.sh
               dest: /opt/

        - name: install nginx
          action: apt name=nginx state=present
          notify: installed nginx

        - name: allow ports
          ufw: 
               rule: allow
               port: 1058
               proto: tcp
          
  handlers:
        - name: installed nginx
          service: name=nginx state=restarted
