- name: copy httpd.conf file
  copy:
            src: /var/lib/jenkins/workspace/ansible/httpd.conf
            dest: /etc/httpd/conf
        
- name: copy index.html file
  copy:
            src: /var/lib/jenkins/workspace/ansible/index.html
            dest: /var/www/html/
        
- name: copy script.sh file
  copy: 
            src: /var/lib/jenkins/workspace/ansible/script.sh
            dest: /opt/

- name: install httpd
  action: yum name=httpd state=present
  notify: installed apache2
        
- name: 
  file:
            path: /opt/logs
            state: directory

- name: reboot the remote server
  reboot:
            msg: "Reboot the server"

- name: Cron job
  cron:
            name: run cron job
            minute: "*"
            job: "/opt/script.sh"
