name: Enforce Branch Pattern

on:
  create:
    branches:
      - '*'

jobs:
  enforce_pattern:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Branch Name
        run: |
          BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          echo "Branch name is: $BRANCH_NAME"
          # Define your branch naming patterns here
          FEATURE="^feature/.*$"
          BUGFIX="^bugfix/.*$"
          HOTFIX="^hotfix/.*$"
          if [[ ! $BRANCH_NAME =~ $FEATURE ]] && [[ ! $BRANCH_NAME =~ $BUGFIX ]] && [[ ! $BRANCH_NAME =~ $HOTFIX ]]; then
            echo "Error: Branch name must start with 'feature/', 'bugfix/' or 'hotfix/'. Deleting the branch..."
            # Delete the branch using GitHub API
            curl -X DELETE -H "Authorization: token ${{ secrets.MY_GITHUB_TOKEN }}" "https://api.github.com/repos/${GITHUB_REPOSITORY}/git/refs/heads/${BRANCH_NAME}"
          fi
