name: Enforce Branch Pattern

on:
  create:
    branches:
      - '*'

jobs:
  enforce_pattern:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Branch Name
        run: echo "Branch name is: ${{ github.ref }}"
